[functions]
  node_bundler = "esbuild"
  external_node_modules = ["astro"]
[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store --no-frozen-lockfile && npx pnpm run build"
